name: Build ViewManager

on:
  push:
    branches: [ main ]
    paths:
      - Fachep.WpfUtils.ViewManager/**
      - Fachep.WpfUtils.ViewManager.Tests/**
      - Directory.*
      - global.json
  pull_request:
    branches: [ main ]
    paths:
      - Fachep.WpfUtils.ViewManager/**
      - Fachep.WpfUtils.ViewManager.Tests/**
      - Directory.*
      - global.json

defaults:
  run:
    shell: pwsh

jobs:
  call_build:
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: write
    with:
      project: ViewManager
      test: true
      pull_request: ${{ github.event_name == 'pull_request' && github.event.number || 0 }}
