name: Build and Deploy

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      project_prefix:
        required: false
        type: string
        default: Fachep.WpfUtils.
      version:
        required: false
        type: string
        default: 0.0.1
      test:
        required: false
        type: boolean
        default: false
      test_suffix:
        required: false
        type: string
        default: .TESTS
      publish:
        required: false
        type: boolean
        default: false
      pull_request:
        required: false
        type: number

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: >
          dotnet build "${{ inputs.project_prefix }}${{ inputs.project }}" --configuration Release --no-restore
          -p:Version="${{ inputs.version }}" -p:SolutionDir="${{ github.workspace }}"

      - name: dotnet pack
        run: >
          dotnet pack "${{ inputs.project_prefix }}${{ inputs.project }}" --configuration Release --no-build
          -o "${{ github.workspace }}/NuGet" -p:Version="${{ inputs.version }}"
          -p:SolutionDir="${{ github.workspace }}"

      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v7
        with:
          name: NuGet
          path: ${{ github.workspace }}/NuGet

      - name: dotnet test
        if: ${{ inputs.test }}
        run: >
          dotnet test --project "${{ inputs.project_prefix }}${{ inputs.project }}${{ inputs.test_suffix }}" --configuration Release
          -- --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml

      - name: ReportGenerator
        if: ${{ inputs.test }}
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.4
        with:
          reports: '**/TestResults/coverage.cobertura.xml'
          targetdir: coveragereport
          reporttypes: Html;MarkdownSummaryGithub
          title: 'Code Coverage'

      - name: Upload Code Coverage Report
        if: ${{ inputs.test }}
        uses: actions/upload-artifact@v7
        with:
          name: CodeCoverage
          path: coveragereport
          if-no-files-found: error

  deploy-nuget:
    if: ${{ inputs.publish }}
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: NuGet

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push NuGet
        run: >
          dotnet nuget push ${{ github.workspace }}\*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json --skip-duplicate

  release:
    if: ${{ inputs.publish }}
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: NuGet

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          working_directory: ${{ github.workspace }}
          files: ./*.nupkg

  post-code-coverage:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.test && inputs.pull_request }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: CodeCoverage

      - uses: marocchino/sticky-pull-request-comment@v3
        with:
          recreate: true
          number: ${{ inputs.pull_request }}
          path: SummaryGithub.md
